services:
  - type: web
    name: ladl-backend
    env: node
    buildCommand: npm install
    startCommand: node server.cjs
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.mmzywkqwiwdrdtkocrtj:[Edward2002@@]@aws-0-eu-west-3.pooler.supabase.com:6543/postgres 