services:
  # Backend API
  - type: web
    name: ladl-backend
    env: node
    buildCommand: npm install
    startCommand: node start.cjs
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.sgcpymrobdjbcpzjmaos:Les_As_De_Auto_2025@aws-0-eu-west-3.pooler.supabase.com:5432/postgres 